<!doctype html><html lang="{{ app()->getLocale() }}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>{{ $label }} 관리업무</title>
<style>body{font-family:system-ui;background:#f5f7fa;color:#182538;margin:0}main{max-width:760px;margin:auto;padding:24px}a{color:inherit}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.card{display:block;background:white;padding:20px;border-radius:14px;text-decoration:none;border:1px solid #dce3eb}.muted{color:#617185;font-size:13px}.number{font-size:28px;font-weight:700}</style></head><body>
@include('partials.erp-home')
<main><a href="{{ route('attendance-app.index') }}">← 내 업무</a><h1>{{ $label }} · 관리업무</h1><p>{{ implode(' · ', $duties) }}</p>
<div class="cards">@foreach($summary as $name => $count)<div class="card"><div class="muted">{{ $name }}</div><div class="number">{{ $count }}</div></div>@endforeach</div>
<h2>담당 업무</h2><div class="cards">@forelse($links as $link)<a class="card" href="{{ $link['url'] }}"><b>{{ $link['label'] }}</b><p class="muted">{{ implode(' · ', array_map(fn($action) => config('job_access.actions.'.$action), $link['actions'])) }}</p></a>@empty<p>담당 업무 권한이 없습니다. 관리자에게 설정을 요청하세요.</p>@endforelse</div>
@if(count($approvals))<h2>승인 대기</h2><p class="muted">내용을 확인한 뒤 승인하세요. 구매는 승인한 예산 한도 안에서만 주문할 수 있습니다.</p>
@foreach($approvals as $row)<form class="card approval" data-url="{{ route('job-approvals.decide', ['module' => $row['module'], 'id' => $row['id']]) }}"><b>{{ $row['title'] }}</b><p>{{ $row['detail'] }}</p>
@if($row['url'])<a href="{{ $row['url'] }}">상세 자료 확인</a>@endif
<input type="hidden" name="version" value="{{ $row['version'] }}">
@if($row['budget'])<p><label>구매 예산 한도 <input name="budget" type="number" min="0.01" step="0.01" required></label><select name="currency"><option>USD</option><option>KRW</option><option>EUR</option><option>CAD</option></select></p>@endif
<p><button type="submit" name="decision" value="approved">승인</button> @if($row['module'] !== 'payroll')<button type="submit" name="decision" value="rejected" formnovalidate>반려</button>@endif</p><p class="result" role="status"></p></form>@endforeach@endif
@if(count($payments))<h2>지급 완료 기록</h2><p class="muted">실제 지급을 확인한 뒤 완료로 기록하세요.</p>
@foreach($payments as $row)<form class="card approval" data-url="{{ route('job-payments.record', ['module' => $row['module'], 'id' => $row['id']]) }}"><b>{{ $row['title'] }}</b><p>{{ $row['detail'] }}</p><input type="hidden" name="version" value="{{ $row['version'] }}"><button type="submit" name="decision" value="paid">지급 완료 처리</button><p class="result" role="status"></p></form>@endforeach@endif
</main><script>document.querySelectorAll('.approval').forEach(function(form){form.addEventListener('submit',async function(e){e.preventDefault();var button=e.submitter;if(!button)return;button.disabled=true;var data=Object.fromEntries(new FormData(form));data.decision=button.value;try{var response=await fetch(form.dataset.url,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},body:JSON.stringify(data)});var result=await response.json();form.querySelector('.result').textContent=result.message||result.error||'처리 실패';if(response.ok && result.success)form.querySelectorAll('button').forEach(function(b){b.disabled=true;});else button.disabled=false;}catch(error){form.querySelector('.result').textContent='연결을 확인하고 다시 시도하세요.';button.disabled=false;}});});</script></body></html>
