<?php

// Explicit endpoint catalog: a newly added endpoint requires a reviewed permission assignment.
return [
    'legacy' => [
        'api_setJobAccess' => ['system', 'edit'],
        'api_actPermit' => ['safety', 'approve'],
        'api_activateApplicant' => ['people', 'edit'],
        'api_addManualWbsWork' => ['progress', 'edit'],
        'api_applyAllOpsItems' => ['reports', 'edit'],
        'api_applyOpsItem' => ['reports', 'edit'],
        'api_approveAttendanceLog' => ['attendance', 'approve'],
        'api_approvePayroll' => ['payroll', 'approve'],
        'api_assignBillingReceipt' => ['contracts', 'edit'],
        'api_assignCrewEmployee' => ['system', 'edit'],
        'api_assignEmployeeTeam' => ['people', 'edit'],
        'api_assignSafetySigner' => ['safety', 'edit'],
        'api_bulkProcessDriveFolder' => ['documents', 'edit'],
        'api_carryOverWeekBoard' => ['progress', 'edit'],
        'api_cleanEmptyRentalRows' => ['office', 'edit'],
        'api_clearBoq' => ['progress', 'delete'],
        'api_clearEquipment' => ['materials', 'delete'],
        'api_clearEquipmentBlock' => ['materials', 'delete'],
        'api_clearSafetyWork' => ['safety', 'delete'],
        'api_clockIn' => ['attendance', 'edit'],
        'api_clockInWithGps' => ['attendance', 'edit'],
        'api_clockInWithTeamQr' => ['attendance', 'edit'],
        'api_clockOut' => ['attendance', 'edit'],
        'api_completeOpsAction' => ['reports', 'edit'],
        'api_confirmDoc' => ['documents', 'edit'],
        'api_confirmMaterialReceipt' => ['materials', 'edit'],
        'api_confirmSelfRegistration' => ['people', 'edit'],
        'api_createDocFolder' => ['documents', 'edit'],
        'api_createGuestLink' => ['system', 'edit'],
        'api_createManagerInvitation' => ['system', 'edit'],
        'api_createRental' => ['office', 'edit'],
        'api_createSafetyCardForWbs' => ['safety', 'edit'],
        'api_createVendor' => ['purchasing', 'edit'],
        'api_decideRfi' => ['progress', 'approve'],
        'api_deleteAttendanceLog' => ['attendance', 'delete'],
        'api_deleteBilling' => ['contracts', 'delete'],
        'api_deleteBillingReceipt' => ['contracts', 'delete'],
        'api_deleteBoqItem' => ['progress', 'delete'],
        'api_deleteCommunicationMessage' => ['system', 'delete'],
        'api_deleteCommunicationRoom' => ['system', 'delete'],
        'api_deleteContract' => ['contracts', 'delete'],
        'api_deleteContractDocument' => ['contracts', 'delete'],
        'api_deleteDoc' => ['documents', 'delete'],
        'api_deleteDocFolder' => ['documents', 'delete'],
        'api_deleteDrawingMark' => ['progress', 'delete'],
        'api_deleteEmployeeAdmin' => ['people', 'delete'],
        'api_deleteEquipmentMany' => ['materials', 'delete'],
        'api_deleteItem' => ['materials', 'delete'],
        'api_deleteItemCategory' => ['materials', 'delete'],
        'api_deleteMaterialReceipt' => ['materials', 'delete'],
        'api_deleteOpsAction' => ['reports', 'delete'],
        'api_deleteOpsBatch' => ['reports', 'delete'],
        'api_deleteOpsLabor' => ['reports', 'delete'],
        'api_deletePayProfile' => ['payroll', 'delete'],
        'api_deleteProjectAdmin' => ['system', 'delete'],
        'api_deleteReportRecipient' => ['system', 'delete'],
        'api_deleteSafetyWork' => ['safety', 'delete'],
        'api_deleteSiteAdmin' => ['system', 'delete'],
        'api_deleteSiteWifi' => ['attendance', 'delete'],
        'api_deleteUserAccess' => ['system', 'delete'],
        'api_deleteWeekBoardLine' => ['progress', 'delete'],
        'api_dismissOpsItem' => ['reports', 'edit'],
        'api_draftBillingFromProgress' => ['contracts', 'edit'],
        'api_draftClaimEvidence' => ['contracts', 'edit'],
        'api_exportBoq' => ['progress', 'export'],
        'api_exportEquipment' => ['materials', 'export'],
        'api_fileSubmittalResearch' => ['progress', 'edit'],
        'api_finalizeAttendanceNow' => ['payroll', 'edit'],
        'api_generateSafetyPlan' => ['safety', 'edit'],
        'api_generateVendorEmailPrompt' => ['purchasing', 'edit'],
        'api_getAiJob' => ['reports', 'view'],
        'api_getAlerts' => ['messages', 'view'],
        'api_getAllFolderFiles' => ['progress', 'view'],
        'api_getApplicantOptions' => ['people', 'view'],
        'api_getApplicants' => ['people', 'view'],
        'api_getAssignableEmployees' => ['people', 'view'],
        'api_getAttendanceDetailed' => ['attendance', 'view'],
        'api_getAttendanceLive' => ['attendance', 'view'],
        'api_getAttendanceLogHistory' => ['attendance', 'view'],
        'api_getAttendanceLogOptions' => ['attendance', 'view'],
        'api_getAttendanceLogs' => ['attendance', 'view'],
        'api_getBillingContracts' => ['contracts', 'view'],
        'api_getBillingOptions' => ['contracts', 'view'],
        'api_getBillings' => ['contracts', 'view'],
        'api_getBoq' => ['progress', 'view'],
        'api_getCardPermits' => ['safety', 'view'],
        'api_getClaimEvidence' => ['contracts', 'view'],
        'api_getClaimPacket' => ['contracts', 'view'],
        'api_getCommunicationAdmin' => ['system', 'view'],
        'api_getCommunicationAdminOptions' => ['system', 'view'],
        'api_getCompanyList' => ['reports', 'view'],
        'api_getCompanyTypes' => ['reports', 'view'],
        'api_getConstructionCommandCenter' => ['reports', 'view'],
        'api_getContractDocuments' => ['contracts', 'view'],
        'api_getContractOptions' => ['contracts', 'view'],
        'api_getContracts' => ['contracts', 'view'],
        'api_getCorrespondence' => ['system', 'view'],
        'api_getCorrespondenceThread' => ['system', 'view'],
        'api_getCrewSetup' => ['system', 'view'],
        'api_getDailyAttendanceDetail' => ['attendance', 'view'],
        'api_getDailyClosing' => ['reports', 'view'],
        'api_getDailyClosings' => ['reports', 'view'],
        'api_getDailyHeadcount' => ['attendance', 'view'],
        'api_getDailyPlan' => ['reports', 'view'],
        'api_getDailyReportPreview' => ['reports', 'view'],
        'api_getDailyTeamMatrix' => ['attendance', 'view'],
        'api_getDocDashboard' => ['documents', 'view'],
        'api_getDocDetail' => ['documents', 'view'],
        'api_getDocExpiring' => ['documents', 'view'],
        'api_getDocFolder' => ['documents', 'view'],
        'api_getDocFolders' => ['documents', 'view'],
        'api_getDocStorageHealth' => ['system', 'view'],
        'api_getDocsForEntity' => ['documents', 'view'],
        'api_getEmployeeAdminList' => ['people', 'view'],
        'api_getEmployeeAdminOptions' => ['people', 'view'],
        'api_getEmployeeDetail' => ['private_hr', 'view'],
        'api_getEmployeeList' => ['people', 'view'],
        'api_getEquipmentChecklistTemplates' => ['materials', 'view'],
        'api_getEquipmentChecks' => ['materials', 'view'],
        'api_getEquipmentList' => ['materials', 'view'],
        'api_getEquipmentStats' => ['materials', 'view'],
        'api_getExpenses' => ['finance', 'view'],
        'api_getFinanceExcelBase64' => ['finance', 'export'],
        'api_getFinanceStats' => ['finance', 'view'],
        'api_getGeofenceSites' => ['attendance', 'view'],
        'api_getGlobalAttendance' => ['attendance', 'view'],
        'api_getGlobalHrOverview' => ['people', 'view'],
        'api_getGuestLinks' => ['system', 'view'],
        'api_getHRData' => ['people', 'view'],
        'api_getHousingList' => ['office', 'view'],
        'api_getHousingStats' => ['office', 'view'],
        'api_getHrAttendanceEvents' => ['attendance', 'view'],
        'api_getHrAttendanceRecords' => ['attendance', 'view'],
        'api_getHrAttendanceSummary' => ['attendance', 'view'],
        'api_getHrDirectory' => ['people', 'view'],
        'api_getInventoryAssetDetail' => ['materials', 'view'],
        'api_getInventoryDashboard' => ['materials', 'view'],
        'api_getItemMaster' => ['materials', 'view'],
        'api_getItemMasterOptions' => ['materials', 'view'],
        'api_getKakaoReminders' => ['system', 'view'],
        'api_getLaborAllocation' => ['progress', 'view'],
        'api_getMailStatus' => ['system', 'view'],
        'api_getMaterialReceipts' => ['materials', 'view'],
        'api_getOpsActions' => ['reports', 'view'],
        'api_getOpsBatch' => ['reports', 'view'],
        'api_getOpsBatches' => ['reports', 'view'],
        'api_getOpsDashboard' => ['reports', 'view'],
        'api_getOpsDigest' => ['reports', 'view'],
        'api_getOpsFeed' => ['reports', 'view'],
        'api_getOpsJob' => ['reports', 'view'],
        'api_getOpsLabor' => ['reports', 'view'],
        'api_getOpsPending' => ['reports', 'view'],
        'api_getOrgSettings' => ['system', 'view'],
        'api_getPayProfileOptions' => ['payroll', 'view'],
        'api_getPayProfiles' => ['payroll', 'view'],
        'api_getPayrollDashboard' => ['payroll', 'view'],
        'api_getPendingAttendanceLogs' => ['attendance', 'view'],
        'api_getPersonnelCard' => ['private_hr', 'view'],
        'api_getPersonnelList' => ['people', 'view'],
        'api_getPersonnelStats' => ['people', 'view'],
        'api_getProcurement' => ['purchasing', 'view'],
        'api_getProjectList' => ['reports', 'view'],
        'api_getProjectProgressSummary' => ['progress', 'view'],
        'api_getProjectWbsTree' => ['progress', 'view'],
        'api_getReceiptClaims' => ['contracts', 'view'],
        'api_getRentalList' => ['office', 'view'],
        'api_getRentalStats' => ['office', 'view'],
        'api_getReportDispatches' => ['reports', 'view'],
        'api_getReportRecipients' => ['system', 'view'],
        'api_getSafetyWorkItems' => ['safety', 'view'],
        'api_getSectionDrawings' => ['progress', 'view'],
        'api_getSectionLines' => ['progress', 'view'],
        'api_getSetupWizardAssets' => ['system', 'view'],
        'api_getSheetMarks' => ['system', 'view'],
        'api_getSiteAdmin' => ['system', 'view'],
        'api_getSiteAdminOptions' => ['system', 'view'],
        'api_getSiteList' => ['reports', 'view'],
        'api_getSiteWifi' => ['attendance', 'view'],
        'api_getSourceDocument' => ['documents', 'view'],
        'api_getSubmittals' => ['progress', 'view'],
        'api_getTeamBoard' => ['people', 'view'],
        'api_getTeamList' => ['reports', 'view'],
        'api_getTodayWbsWork' => ['progress', 'view'],
        'api_getToolList' => ['materials', 'view'],
        'api_getToolStats' => ['materials', 'view'],
        'api_getToolTransactions' => ['materials', 'view'],
        'api_getTradeReportBoard' => ['reports', 'view'],
        'api_getUserAccessList' => ['system', 'view'],
        'api_getUserAccessOptions' => ['system', 'view'],
        'api_getVehicleList' => ['office', 'view'],
        'api_getVehicleStats' => ['office', 'view'],
        'api_getVendorList' => ['purchasing', 'view'],
        'api_getVendorReplies' => ['purchasing', 'view'],
        'api_getWbsCompanyOptions' => ['progress', 'view'],
        'api_getWbsLabor' => ['progress', 'view'],
        'api_getWbsPickList' => ['progress', 'view'],
        'api_getWeekBoard' => ['progress', 'view'],
        'api_getWeekBoard3Weeks' => ['progress', 'view'],
        'api_getWeeklyPlan' => ['progress', 'view'],
        'api_grantEmployeeAccount' => ['system', 'edit'],
        'api_importBoq' => ['progress', 'edit'],
        'api_importClaimSource' => ['contracts', 'edit'],
        'api_importContractSheet' => ['contracts', 'edit'],
        'api_insertWbsRow' => ['progress', 'edit'],
        'api_inviteApplicant' => ['people', 'edit'],
        'api_issuePermitsForCard' => ['safety', 'edit'],
        'api_linkDoc' => ['documents', 'edit'],
        'api_linkReceiptLine' => ['finance', 'edit'],
        'api_listGcClaims' => ['contracts', 'view'],
        'api_markWbsStatus' => ['progress', 'edit'],
        'api_nfcAssignHousing' => ['office', 'edit'],
        'api_nfcAssignVehicle' => ['office', 'edit'],
        'api_opsIngest' => ['reports', 'edit'],
        'api_payPayroll' => ['payroll', 'pay'],
        'api_previewContractSheet' => ['contracts', 'view'],
        'api_previewGcClaim' => ['contracts', 'view'],
        'api_processEquipmentRentalContracts' => ['contracts', 'edit'],
        'api_processInventoryPhotos' => ['materials', 'edit'],
        'api_processRentalContracts' => ['contracts', 'edit'],
        'api_processWbsManual' => ['progress', 'edit'],
        'api_recommendSafetyProgress' => ['safety', 'edit'],
        'api_recordInstallation' => ['progress', 'edit'],
        'api_registerApplicantBadge' => ['people', 'edit'],
        'api_rejectApplicant' => ['people', 'approve'],
        'api_rejectAttendanceLog' => ['attendance', 'approve'],
        'api_relatedDrawings' => ['progress', 'view'],
        'api_requestCorrection' => ['attendance', 'edit'],
        'api_requestVendorData' => ['purchasing', 'edit'],
        'api_researchSubmittal' => ['progress', 'edit'],
        'api_restoreAttendanceLog' => ['attendance', 'edit'],
        'api_resyncApplicant' => ['people', 'edit'],
        'api_returnRental' => ['office', 'edit'],
        'api_revertOpsItem' => ['reports', 'edit'],
        'api_reviewClaimRecord' => ['contracts', 'approve'],
        'api_reviewExpense' => ['finance', 'approve'],
        'api_revokeGuestLink' => ['system', 'edit'],
        'api_revokeManagerInvitation' => ['system', 'edit'],
        'api_revokeNewManagerInvitation' => ['system', 'edit'],
        'api_runPayroll' => ['payroll', 'edit'],
        'api_saveAttendanceLog' => ['attendance', 'edit'],
        'api_saveBilling' => ['contracts', 'edit'],
        'api_saveBillingReceipt' => ['contracts', 'edit'],
        'api_saveBoqItem' => ['progress', 'edit'],
        'api_saveClaimLine' => ['contracts', 'edit'],
        'api_saveClaimRecord' => ['contracts', 'edit'],
        'api_saveCommunicationMessage' => ['system', 'edit'],
        'api_saveCommunicationRoom' => ['system', 'edit'],
        'api_saveContract' => ['contracts', 'edit'],
        'api_saveCrewCompany' => ['system', 'edit'],
        'api_saveCrewTeam' => ['system', 'edit'],
        'api_saveDailyPlan' => ['reports', 'edit'],
        'api_saveDrawingMark' => ['progress', 'edit'],
        'api_saveEmployeeAdmin' => ['people', 'edit'],
        'api_saveEquipmentChecklistItem' => ['materials', 'edit'],
        'api_saveItem' => ['materials', 'edit'],
        'api_saveItemCategory' => ['materials', 'edit'],
        'api_saveKakaoReminder' => ['system', 'edit'],
        'api_saveMaterialReceipt' => ['materials', 'edit'],
        'api_saveOpsAction' => ['reports', 'edit'],
        'api_saveOpsLabor' => ['reports', 'edit'],
        'api_saveOrgSettings' => ['system', 'edit'],
        'api_savePayProfile' => ['payroll', 'edit'],
        'api_saveProjectAdmin' => ['system', 'edit'],
        'api_saveReportRecipient' => ['system', 'edit'],
        'api_saveSafetyPlan' => ['safety', 'edit'],
        'api_saveSafetyWorkItems' => ['safety', 'edit'],
        'api_saveSiteAdmin' => ['system', 'edit'],
        'api_saveSiteWifi' => ['attendance', 'edit'],
        'api_saveSubmittal' => ['progress', 'edit'],
        'api_saveUserAccess' => ['system', 'edit'],
        'api_saveWeekBoardLine' => ['progress', 'edit'],
        'api_saveWeekBoardLines' => ['progress', 'edit'],
        'api_saveWorkSection' => ['progress', 'edit'],
        'api_searchDocs' => ['documents', 'view'],
        'api_sendDailyReport' => ['reports', 'edit'],
        'api_sendTestMail' => ['system', 'edit'],
        'api_sendVendorEmail' => ['purchasing', 'edit'],
        'api_setApplicantInterview' => ['people', 'edit'],
        'api_setApplicantSafety' => ['people', 'edit'],
        'api_setAttendanceLogStatus' => ['attendance', 'approve'],
        'api_setBillingStatus' => ['contracts', 'approve'],
        'api_setCompanyType' => ['system', 'edit'],
        'api_setMySiteGeofence' => ['attendance', 'edit'],
        'api_setSectionSheets' => ['progress', 'edit'],
        'api_setSheetScale' => ['system', 'edit'],
        'api_setUserAccessStatus' => ['system', 'edit'],
        'api_setWeekBoardStatus' => ['progress', 'edit'],
        'api_setupSite' => ['system', 'edit'],
        'api_startDailyClosing' => ['reports', 'edit'],
        'api_submitBatchPhotoScan' => ['attendance', 'edit'],
        'api_submitNfcTag' => ['attendance', 'edit'],
        'api_submitRfi' => ['progress', 'edit'],
        'api_submittalComms' => ['progress', 'edit'],
        'api_suggestSiteGeofence' => ['attendance', 'edit'],
        'api_syncCommunicationRoomMembers' => ['system', 'edit'],
        'api_syncOfflineAttendance' => ['attendance', 'edit'],
        'api_syncWorkerStatus' => ['people', 'edit'],
        'api_toggleWeekCommit' => ['system', 'edit'],
        'api_tradeReportBoard' => ['reports', 'edit'],
        'api_tradeReportReopen' => ['reports', 'approve'],
        'api_translateToEnglish' => ['reports', 'edit'],
        'api_universalAIScan' => ['reports', 'edit'],
        'api_updateAlertStatus' => ['messages', 'edit'],
        'api_updateDrawingSheet' => ['progress', 'edit'],
        'api_updateOpsBatch' => ['reports', 'edit'],
        'api_updateProcurement' => ['purchasing', 'edit'],
        'api_updateWbsRow' => ['progress', 'edit'],
        'api_uploadEmployeePhoto' => ['people', 'edit'],
        'setupInventoryFolders' => ['materials', 'edit'],
        'setupInventorySheets' => ['materials', 'edit'],
        'setupRentalSheet' => ['office', 'edit'],
    ],
    'controllers' => [
        'WorkerEnrollmentController' => ['_module' => 'people', 'index' => ['people', 'view'], 'approve' => ['people', 'edit'], 'reject' => ['people', 'edit']],
        'MobileOpsRoomController' => ['_module' => 'reports'],
        'MobileDocumentController' => ['_module' => 'documents'],
        'MaterialReceiptController' => ['_module' => 'materials', 'confirmMobile' => ['materials', 'edit']],
        'IntegratedDocumentController' => ['_module' => 'documents', 'show' => ['documents', 'export']],
        'DocumentIntelligenceController' => ['_module' => 'documents', 'extractSubmittals' => ['progress', 'edit']],
        'ProjectContractDocumentController' => ['_module' => 'contracts'],
        'PayrollController' => ['_module' => 'payroll'],
        'GcClaimExportController' => ['_module' => 'contracts'],
        'HrAttendanceExportController' => ['_module' => 'attendance'],
        'W9FormController' => ['_module' => 'private_hr'],
        'PurchaseRequestController' => ['_module' => 'purchasing', 'mobile' => ['purchasing', 'view'], 'store' => ['purchasing', 'view'], 'upload' => ['purchasing', 'view'], 'action' => ['purchasing', 'edit']],
        'PurchaseAnalysisController' => ['_module' => 'purchasing', 'store' => ['purchasing', 'view']],
        'ProcurementController' => ['_module' => 'purchasing'],
        'WbsManualController' => ['_module' => 'progress'],
        'WbsPhotoController' => ['_module' => 'progress'],
        'WbsScheduleController' => ['_module' => 'progress'],
        'DrawingSheetController' => ['_module' => 'progress'],
        'WeekBoardDraftController' => ['_module' => 'progress'],
        'OpsVoiceController' => ['_module' => 'reports'],
        'OpsPhotoController' => ['_module' => 'reports'],
        'OpsMeetingController' => ['_module' => 'reports'],
        'MobileEquipmentController' => ['_module' => 'materials'],
        'EquipmentApiController' => ['_module' => 'materials'],
        'EquipmentChecklistController' => ['_module' => 'materials', 'stickerSheet' => ['materials', 'export'], 'sticker' => ['materials', 'export']],
        'VehicleApiController' => ['_module' => 'office'],
        'MobileExpenseController' => ['_module' => 'finance'],
        'ExpensePreApprovalController' => ['_module' => 'finance'],
        'AdminUploadController' => ['_module' => 'system', 'contractDocument' => ['contracts', 'edit']],
        'OrgLogoController' => ['_module' => 'system'],
        'CompanySwitchController' => ['_module' => 'reports', '__invoke' => ['reports', 'view']],
        'AssistantWorkspaceController' => ['_module' => 'reports', 'status' => ['reports', 'view'], 'report' => ['reports', 'view'], 'index' => ['reports', 'view'], 'ask' => ['reports', 'view'], 'show' => ['reports', 'view'], 'export' => ['reports', 'export'], 'run' => ['reports', 'edit']],
        'EmailAiInboxController' => ['_module' => 'documents'],
        'QrPrintController' => ['_module' => 'attendance'],
        'AttendanceNoticeController' => ['_module' => 'attendance'],
        'AttendanceGeoController' => ['_module' => 'attendance'],
        'PushSubscriptionController' => ['_module' => 'messages'],
    ],
];
